package com.project.model;
// Generated Mar 10, 2018 11:16:05 AM by Hibernate Tools 5.2.3.Final

import java.io.Serializable;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;

/**
 * Card generated by hbm2java
 */
@Entity
@Table(name = "card", catalog = "project_mgmt")
public class Card implements java.io.Serializable {

	private Integer cardId;
	private List list;
	private Serializable description;
	private String status;
	private String priority;
	private Integer reportedById;
	private Integer assignedToId;
	private Integer timeTracking;

	public Card() {
	}

	public Card(List list) {
		this.list = list;
	}

	public Card(List list, Serializable description, String status, String priority, Integer reportedById,
			Integer assignedToId, Integer timeTracking) {
		this.list = list;
		this.description = description;
		this.status = status;
		this.priority = priority;
		this.reportedById = reportedById;
		this.assignedToId = assignedToId;
		this.timeTracking = timeTracking;
	}

	@Id
	@GeneratedValue(strategy = IDENTITY)

	@Column(name = "card_id", unique = true, nullable = false)
	public Integer getCardId() {
		return this.cardId;
	}

	public void setCardId(Integer cardId) {
		this.cardId = cardId;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "list_id", nullable = false)
	public List getList() {
		return this.list;
	}

	public void setList(List list) {
		this.list = list;
	}

	@Column(name = "description")
	public Serializable getDescription() {
		return this.description;
	}

	public void setDescription(Serializable description) {
		this.description = description;
	}

	@Column(name = "status", length = 45)
	public String getStatus() {
		return this.status;
	}

	public void setStatus(String status) {
		this.status = status;
	}

	@Column(name = "priority", length = 45)
	public String getPriority() {
		return this.priority;
	}

	public void setPriority(String priority) {
		this.priority = priority;
	}

	@Column(name = "reported_by_id")
	public Integer getReportedById() {
		return this.reportedById;
	}

	public void setReportedById(Integer reportedById) {
		this.reportedById = reportedById;
	}

	@Column(name = "assigned_to_id")
	public Integer getAssignedToId() {
		return this.assignedToId;
	}

	public void setAssignedToId(Integer assignedToId) {
		this.assignedToId = assignedToId;
	}

	@Column(name = "time_tracking")
	public Integer getTimeTracking() {
		return this.timeTracking;
	}

	public void setTimeTracking(Integer timeTracking) {
		this.timeTracking = timeTracking;
	}

}
