package com.project.model;
// Generated Mar 4, 2018 7:08:47 PM by Hibernate Tools 5.2.3.Final

import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.OneToMany;
import javax.persistence.Table;

/**
 * Project generated by hbm2java
 */
@Entity
@Table(name = "project", catalog = "project_mgmt")
public class Project implements java.io.Serializable {

	/**
	 * 
	 */
	private static final long serialVersionUID = 8385917480528616608L;
	private Integer projectId;
	private Board board;
	private ProjectType projectType;
	private String name;
	private Set<UserHasProject> userHasProjects = new HashSet<UserHasProject>(0);

	public Project() {
	}

	public Project(Board board, ProjectType projectType) {
		this.board = board;
		this.projectType = projectType;
	}

	public Project(Board board, ProjectType projectType, String name, Set<UserHasProject> userHasProjects) {
		this.board = board;
		this.projectType = projectType;
		this.name = name;
		this.userHasProjects = userHasProjects;
	}

	@Id
	@GeneratedValue(strategy = IDENTITY)

	@Column(name = "project_id", unique = true, nullable = false)
	public Integer getProjectId() {
		return this.projectId;
	}

	public void setProjectId(Integer projectId) {
		this.projectId = projectId;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "board_id", nullable = false)
	public Board getBoard() {
		return this.board;
	}

	public void setBoard(Board board) {
		this.board = board;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "project_type_id", nullable = false)
	public ProjectType getProjectType() {
		return this.projectType;
	}

	public void setProjectType(ProjectType projectType) {
		this.projectType = projectType;
	}

	@Column(name = "name", length = 45)
	public String getName() {
		return this.name;
	}

	public void setName(String name) {
		this.name = name;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "project")
	public Set<UserHasProject> getUserHasProjects() {
		return this.userHasProjects;
	}

	public void setUserHasProjects(Set<UserHasProject> userHasProjects) {
		this.userHasProjects = userHasProjects;
	}

}
