package com.project.model;
// Generated Mar 4, 2018 7:08:47 PM by Hibernate Tools 5.2.3.Final

import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.OneToMany;
import javax.persistence.Table;

/**
 * ProjectType generated by hbm2java
 */
@Entity
@Table(name = "project_type", catalog = "project_mgmt")
public class ProjectType implements java.io.Serializable {

	/**
	 * 
	 */
	private static final long serialVersionUID = -6516471133933681895L;
	private Integer projectTypeId;
	private String projectType;
	private Set<Project> projects = new HashSet<Project>(0);

	public ProjectType() {
	}

	public ProjectType(String projectType, Set<Project> projects) {
		this.projectType = projectType;
		this.projects = projects;
	}

	@Id
	@GeneratedValue(strategy = IDENTITY)

	@Column(name = "project_type_id", unique = true, nullable = false)
	public Integer getProjectTypeId() {
		return this.projectTypeId;
	}

	public void setProjectTypeId(Integer projectTypeId) {
		this.projectTypeId = projectTypeId;
	}

	@Column(name = "project_type", length = 45)
	public String getProjectType() {
		return this.projectType;
	}

	public void setProjectType(String projectType) {
		this.projectType = projectType;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "projectType")
	public Set<Project> getProjects() {
		return this.projects;
	}

	public void setProjects(Set<Project> projects) {
		this.projects = projects;
	}

}
