package com.project.model;
// Generated Mar 10, 2018 11:16:05 AM by Hibernate Tools 5.2.3.Final

import static javax.persistence.GenerationType.IDENTITY;

import java.util.HashSet;
import java.util.Set;

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import javax.persistence.Id;
import javax.persistence.OneToMany;
import javax.persistence.Table;

import com.fasterxml.jackson.annotation.JsonIgnoreProperties;

/**
 * Role generated by hbm2java
 */
@Entity
@Table(name = "role", catalog = "proman_db")
@JsonIgnoreProperties({"hibernateLazyInitializer", "handler", "userHasProjects"})
public class Role implements java.io.Serializable {

	/**
	 * 
	 */
	private static final long serialVersionUID = 8929573035864919362L;
	private Integer roleId;
	private String role;
	private Set<UserHasProject> userHasProjects = new HashSet<UserHasProject>(0);

	public Role() {
	}

	public Role(String role) {
		this.role = role;
	}

	public Role(String role, Set<UserHasProject> userHasProjects) {
		this.role = role;
		this.userHasProjects = userHasProjects;
	}

	@Id
	@GeneratedValue(strategy = IDENTITY)

	@Column(name = "role_id", unique = true, nullable = false)
	public Integer getRoleId() {
		return this.roleId;
	}

	public void setRoleId(Integer roleId) {
		this.roleId = roleId;
	}

	@Column(name = "role", nullable = false, length = 45)
	public String getRole() {
		return this.role;
	}

	public void setRole(String role) {
		this.role = role;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "role")
	
	public Set<UserHasProject> getUserHasProjects() {
		return this.userHasProjects;
	}

	public void setUserHasProjects(Set<UserHasProject> userHasProjects) {
		this.userHasProjects = userHasProjects;
	}
	
}
