package com.project.model;
// Generated Mar 10, 2018 11:16:05 AM by Hibernate Tools 5.2.3.Final

import javax.persistence.Column;
import javax.persistence.Embeddable;

import com.google.gson.Gson;

/**
 * UserHasProjectId generated by hbm2java
 */
@Embeddable
public class UserHasProjectId implements java.io.Serializable {

	private int userId;
	private int projectId;

	public UserHasProjectId() {
	}

	public UserHasProjectId(int userId, int projectId) {
		this.userId = userId;
		this.projectId = projectId;
	}

	@Column(name = "user_id", nullable = false)
	public int getUserId() {
		return this.userId;
	}

	public void setUserId(int userId) {
		this.userId = userId;
	}

	@Column(name = "project_id", nullable = false)
	public int getProjectId() {
		return this.projectId;
	}

	public void setProjectId(int projectId) {
		this.projectId = projectId;
	}

	public boolean equals(Object other) {
		if ((this == other))
			return true;
		if ((other == null))
			return false;
		if (!(other instanceof UserHasProjectId))
			return false;
		UserHasProjectId castOther = (UserHasProjectId) other;

		return (this.getUserId() == castOther.getUserId()) && (this.getProjectId() == castOther.getProjectId());
	}

	public int hashCode() {
		int result = 17;

		result = 37 * result + this.getUserId();
		result = 37 * result + this.getProjectId();
		return result;
	}

}
