spring:
  jpa: 
    show-sql: true
    hibernate.ddl-auto: update
    database-platform: org.hibernate.dialect.MySQLDialect
  datasource:
    url: jdbc:mysql://localhost:3306/proman_db
    username: root
    password: mysql
    driverClassName: com.mysql.jdbc.Driver
    
upload.file.directory: upload
