package com.trackattr.model;
// Generated Mar 4, 2018 12:31:03 PM by Hibernate Tools 5.2.3.Final

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.Table;

/**
 * TrackerAttribute generated by hbm2java
 */
@Entity
@Table(name = "tracker_attribute", catalog = "proman_db")
public class TrackerAttribute implements java.io.Serializable {

	/**
	 * 
	 */
	private static final long serialVersionUID = -7282501792852936084L;
	private Integer id;
	private String name;

	public TrackerAttribute() {
	}

	public TrackerAttribute(String name) {
		this.name = name;
	}

	@Id
	@GeneratedValue(strategy = IDENTITY)

	@Column(name = "id", unique = true, nullable = false)
	public Integer getId() {
		return this.id;
	}

	public void setId(Integer id) {
		this.id = id;
	}

	@Column(name = "name", length = 45)
	public String getName() {
		return this.name;
	}

	public void setName(String name) {
		this.name = name;
	}

}
