package com.issuetrack.model;
// Generated Mar 10, 2018 9:58:47 PM by Hibernate Tools 5.2.3.Final

import static javax.persistence.GenerationType.IDENTITY;

import java.util.ArrayList;
import java.util.Date;
import java.util.List;

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import javax.persistence.Id;
import javax.persistence.OneToMany;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

import com.fasterxml.jackson.annotation.JsonIgnore;

/**
 * Issue generated by hbm2java
 */
@Entity
@Table(name = "issue", catalog = "issue_track")
public class Issue implements java.io.Serializable {

	/**
	 * 
	 */
	private static final long serialVersionUID = -1394921912293833993L;
	private Integer issueId;
	private String summary;
	private Date creationDate;
	private String description;
	private String type;
	private String category;
	private Date dueDate;
	private Integer reportedById;
	private Integer assignToId;
	private Integer estimate;
	private Float timeSpent;
	private String statusCode;
	private int severityCode;
	private String priorityCode;
	private int projectId;
	@JsonIgnore
	private List<Comment> comments = new ArrayList<Comment>(0);

	public Issue() {
	}

	public Issue(String priorityCode, int projectId) {
		this.priorityCode = priorityCode;
		this.projectId = projectId;
	}

	public Issue(String summary, Date creationDate, String description, String type, String category, Date dueDate,
			Integer reportedById, Integer assignToId, Integer estimate, Float timeSpent, String statusCode,
			int severityCode, String priorityCode, int projectId, List<Comment> comments) {
		this.summary = summary;
		this.creationDate = creationDate;
		this.description = description;
		this.type = type;
		this.category = category;
		this.dueDate = dueDate;
		this.reportedById = reportedById;
		this.assignToId = assignToId;
		this.estimate = estimate;
		this.timeSpent = timeSpent;
		this.statusCode = statusCode;
		this.severityCode = severityCode;
		this.priorityCode = priorityCode;
		this.projectId = projectId;
		this.comments = comments;
	}

	@Id
	@GeneratedValue(strategy = IDENTITY)

	@Column(name = "issue_id", unique = true, nullable = false)
	public Integer getIssueId() {
		return this.issueId;
	}

	public void setIssueId(Integer issueId) {
		this.issueId = issueId;
	}

	@Column(name = "summary", length = 45)
	public String getSummary() {
		return this.summary;
	}

	public void setSummary(String summary) {
		this.summary = summary;
	}

	@Temporal(TemporalType.DATE)
	@Column(name = "creation_date", length = 10)
	public Date getCreationDate() {
		return this.creationDate;
	}

	public void setCreationDate(Date creationDate) {
		this.creationDate = creationDate;
	}

	@Column(name = "description")
	public String getDescription() {
		return this.description;
	}

	public void setDescription(String description) {
		this.description = description;
	}

	@Column(name = "type", length = 45)
	public String getType() {
		return this.type;
	}

	public void setType(String type) {
		this.type = type;
	}

	@Column(name = "category", length = 45)
	public String getCategory() {
		return this.category;
	}

	public void setCategory(String category) {
		this.category = category;
	}

	@Temporal(TemporalType.DATE)
	@Column(name = "due_date", length = 10)
	public Date getDueDate() {
		return this.dueDate;
	}

	public void setDueDate(Date dueDate) {
		this.dueDate = dueDate;
	}

	@Column(name = "reported_by_id")
	public Integer getReportedById() {
		return this.reportedById;
	}

	public void setReportedById(Integer reportedById) {
		this.reportedById = reportedById;
	}

	@Column(name = "assign_to_id")
	public Integer getAssignToId() {
		return this.assignToId;
	}

	public void setAssignToId(Integer assignToId) {
		this.assignToId = assignToId;
	}

	@Column(name = "estimate")
	public Integer getEstimate() {
		return this.estimate;
	}

	public void setEstimate(Integer estimate) {
		this.estimate = estimate;
	}

	@Column(name = "time_spent", precision = 12, scale = 0)
	public Float getTimeSpent() {
		return this.timeSpent;
	}

	public void setTimeSpent(Float timeSpent) {
		this.timeSpent = timeSpent;
	}

	@Column(name = "status_code", length = 45)
	public String getStatusCode() {
		return this.statusCode;
	}

	public void setStatusCode(String statusCode) {
		this.statusCode = statusCode;
	}

	@Column(name = "severity_code")
	public int getSeverityCode() {
		return this.severityCode;
	}

	public void setSeverityCode(int severityCode) {
		this.severityCode = severityCode;
	}

	@Column(name = "priority_code", nullable = false)
	public String getPriorityCode() {
		return this.priorityCode;
	}

	public void setPriorityCode(String priorityCode) {
		this.priorityCode = priorityCode;
	}

	@Column(name = "project_id", nullable = false)
	public int getProjectId() {
		return this.projectId;
	}

	public void setProjectId(int projectId) {
		this.projectId = projectId;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "issue")
	public List<Comment> getComments() {
		return this.comments;
	}

	public void setComments(List<Comment> comments) {
		this.comments = comments;
	}

}
