package com.user.model;
// Generated Mar 4, 2018 12:32:48 PM by Hibernate Tools 5.2.3.Final

import java.io.Serializable;
import java.util.Date;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * Activitylog generated by hbm2java
 */
@Entity
@Table(name = "activitylog", catalog = "user_service")
public class Activitylog implements java.io.Serializable {

	/**
	 * 
	 */
	private static final long serialVersionUID = -676788837932132675L;
	private Integer logId;
	private String entityName;
	private Date logDate;
	private Serializable description;

	public Activitylog() {
	}

	public Activitylog(String entityName, Date logDate, Serializable description) {
		this.entityName = entityName;
		this.logDate = logDate;
		this.description = description;
	}

	@Id
	@GeneratedValue(strategy = IDENTITY)

	@Column(name = "log_id", unique = true, nullable = false)
	public Integer getLogId() {
		return this.logId;
	}

	public void setLogId(Integer logId) {
		this.logId = logId;
	}

	@Column(name = "entity_name", length = 45)
	public String getEntityName() {
		return this.entityName;
	}

	public void setEntityName(String entityName) {
		this.entityName = entityName;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "log_date", length = 19)
	public Date getLogDate() {
		return this.logDate;
	}

	public void setLogDate(Date logDate) {
		this.logDate = logDate;
	}

	@Column(name = "description")
	public Serializable getDescription() {
		return this.description;
	}

	public void setDescription(Serializable description) {
		this.description = description;
	}

}
