package com.user.model;
// Generated Mar 4, 2018 12:32:48 PM by Hibernate Tools 5.2.3.Final

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.GeneratedValue;
import javax.persistence.GenerationType;
import javax.persistence.Id;
import javax.persistence.Table;

/**
 * User generated by hbm2java
 */
@Entity
@Table(name = "user", catalog = "user_service")
public class User implements java.io.Serializable {

	/**
	 * 
	 */
	private static final long serialVersionUID = 5958983239401484432L;
	private Integer userId;
	private String userName;
	private String passwordHash;
	private String email;
	private String jobTitle;
	private String organisation;
	private String profileImages;
	private String name;
	private String userRole;

	public User() {
	}

	public User(String userName, String passwordHash) {
		this.userName = userName;
		this.passwordHash = passwordHash;
	}

	public User(String userName, String passwordHash, String email, String jobTitle, String organisation,
			String profileImages,String name,String userRole) {
		this.userName = userName;
		this.passwordHash = passwordHash;
		this.email = email;
		this.jobTitle = jobTitle;
		this.organisation = organisation;
		this.profileImages = profileImages;
		this.name = name;
		this.userRole = userRole;
	}

	
	@Id
	@GeneratedValue(strategy = GenerationType.AUTO)

	@Column(name = "user_id", unique = true, nullable = false)
	public Integer getUserId() {
		return this.userId;
	}

	public void setUserId(Integer userId) {
		this.userId = userId;
	}

	@Column(name = "user_name", nullable = false, length = 45)
	public String getUserName() {
		return this.userName;
	}

	public void setUserName(String userName) {
		this.userName = userName;
	}

	@Column(name = "password_hash", nullable = false, length = 60)
	public String getPasswordHash() {
		return this.passwordHash;
	}

	public void setPasswordHash(String passwordHash) {
		this.passwordHash = passwordHash;
	}

	@Column(name = "email", length = 45)
	public String getEmail() {
		return this.email;
	}

	public void setEmail(String email) {
		this.email = email;
	}

	@Column(name = "job_title", length = 45)
	public String getJobTitle() {
		return this.jobTitle;
	}

	public void setJobTitle(String jobTitle) {
		this.jobTitle = jobTitle;
	}

	@Column(name = "organisation", length = 45)
	public String getOrganisation() {
		return this.organisation;
	}

	public void setOrganisation(String organisation) {
		this.organisation = organisation;
	}

	@Column(name = "profile_images", length = 45)
	public String getProfileImages() {
		return this.profileImages;
	}

	public void setProfileImages(String profileImages) {
		this.profileImages = profileImages;
	}

	@Column(name = "name", length = 100)
	public String getName() {
		return this.name;
	}

	public void setName(String name) {
		this.name = name;
	}

	@Column(name = "user_role",length = 45)
	public String getUserRole() {
		return this.userRole;
	}

	public void setUserRole(String userRole) {
		this.userRole = userRole;
	}

}
